// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorResponseErrorCode.
const (
	NOCANDIDATE ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND    ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS    ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED    ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS  ErrorResponseErrorCode = "TEAM_EXISTS"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestCreateJSONBody defines parameters for PostPullRequestCreate.
type PostPullRequestCreateJSONBody struct {
	AuthorId        string `json:"author_id"`
	PullRequestId   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody PostPullRequestCreateJSONBody

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostPullRequestCreateWithBody request with any body
	PostPullRequestCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPullRequestCreate(ctx context.Context, body PostPullRequestCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostPullRequestMergeWithBody request with any body
	PostPullRequestMergeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPullRequestMerge(ctx context.Context, body PostPullRequestMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostPullRequestReassignWithBody request with any body
	PostPullRequestReassignWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPullRequestReassign(ctx context.Context, body PostPullRequestReassignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTeamAddWithBody request with any body
	PostTeamAddWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTeamAdd(ctx context.Context, body PostTeamAddJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTeamGet request
	GetTeamGet(ctx context.Context, params *GetTeamGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersGetReview request
	GetUsersGetReview(ctx context.Context, params *GetUsersGetReviewParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostUsersSetIsActiveWithBody request with any body
	PostUsersSetIsActiveWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostUsersSetIsActive(ctx context.Context, body PostUsersSetIsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostPullRequestCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestCreateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPullRequestCreate(ctx context.Context, body PostPullRequestCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestCreateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPullRequestMergeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestMergeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPullRequestMerge(ctx context.Context, body PostPullRequestMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestMergeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPullRequestReassignWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestReassignRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPullRequestReassign(ctx context.Context, body PostPullRequestReassignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestReassignRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTeamAddWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTeamAddRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTeamAdd(ctx context.Context, body PostTeamAddJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTeamAddRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTeamGet(ctx context.Context, params *GetTeamGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTeamGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersGetReview(ctx context.Context, params *GetUsersGetReviewParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersGetReviewRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUsersSetIsActiveWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUsersSetIsActiveRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUsersSetIsActive(ctx context.Context, body PostUsersSetIsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUsersSetIsActiveRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostPullRequestCreateRequest calls the generic PostPullRequestCreate builder with application/json body
func NewPostPullRequestCreateRequest(server string, body PostPullRequestCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPullRequestCreateRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPullRequestCreateRequestWithBody generates requests for PostPullRequestCreate with any type of body
func NewPostPullRequestCreateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pullRequest/create")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostPullRequestMergeRequest calls the generic PostPullRequestMerge builder with application/json body
func NewPostPullRequestMergeRequest(server string, body PostPullRequestMergeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPullRequestMergeRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPullRequestMergeRequestWithBody generates requests for PostPullRequestMerge with any type of body
func NewPostPullRequestMergeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pullRequest/merge")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostPullRequestReassignRequest calls the generic PostPullRequestReassign builder with application/json body
func NewPostPullRequestReassignRequest(server string, body PostPullRequestReassignJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPullRequestReassignRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPullRequestReassignRequestWithBody generates requests for PostPullRequestReassign with any type of body
func NewPostPullRequestReassignRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pullRequest/reassign")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostTeamAddRequest calls the generic PostTeamAdd builder with application/json body
func NewPostTeamAddRequest(server string, body PostTeamAddJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTeamAddRequestWithBody(server, "application/json", bodyReader)
}

// NewPostTeamAddRequestWithBody generates requests for PostTeamAdd with any type of body
func NewPostTeamAddRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/team/add")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTeamGetRequest generates requests for GetTeamGet
func NewGetTeamGetRequest(server string, params *GetTeamGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/team/get")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "team_name", runtime.ParamLocationQuery, params.TeamName); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersGetReviewRequest generates requests for GetUsersGetReview
func NewGetUsersGetReviewRequest(server string, params *GetUsersGetReviewParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/getReview")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostUsersSetIsActiveRequest calls the generic PostUsersSetIsActive builder with application/json body
func NewPostUsersSetIsActiveRequest(server string, body PostUsersSetIsActiveJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostUsersSetIsActiveRequestWithBody(server, "application/json", bodyReader)
}

// NewPostUsersSetIsActiveRequestWithBody generates requests for PostUsersSetIsActive with any type of body
func NewPostUsersSetIsActiveRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/setIsActive")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostPullRequestCreateWithBodyWithResponse request with any body
	PostPullRequestCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestCreateResponse, error)

	PostPullRequestCreateWithResponse(ctx context.Context, body PostPullRequestCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestCreateResponse, error)

	// PostPullRequestMergeWithBodyWithResponse request with any body
	PostPullRequestMergeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestMergeResponse, error)

	PostPullRequestMergeWithResponse(ctx context.Context, body PostPullRequestMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestMergeResponse, error)

	// PostPullRequestReassignWithBodyWithResponse request with any body
	PostPullRequestReassignWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestReassignResponse, error)

	PostPullRequestReassignWithResponse(ctx context.Context, body PostPullRequestReassignJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestReassignResponse, error)

	// PostTeamAddWithBodyWithResponse request with any body
	PostTeamAddWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTeamAddResponse, error)

	PostTeamAddWithResponse(ctx context.Context, body PostTeamAddJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTeamAddResponse, error)

	// GetTeamGetWithResponse request
	GetTeamGetWithResponse(ctx context.Context, params *GetTeamGetParams, reqEditors ...RequestEditorFn) (*GetTeamGetResponse, error)

	// GetUsersGetReviewWithResponse request
	GetUsersGetReviewWithResponse(ctx context.Context, params *GetUsersGetReviewParams, reqEditors ...RequestEditorFn) (*GetUsersGetReviewResponse, error)

	// PostUsersSetIsActiveWithBodyWithResponse request with any body
	PostUsersSetIsActiveWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUsersSetIsActiveResponse, error)

	PostUsersSetIsActiveWithResponse(ctx context.Context, body PostUsersSetIsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUsersSetIsActiveResponse, error)
}

type PostPullRequestCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		Pr *PullRequest `json:"pr,omitempty"`
	}
	JSON404 *ErrorResponse
	JSON409 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostPullRequestCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPullRequestCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostPullRequestMergeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Pr *PullRequest `json:"pr,omitempty"`
	}
	JSON404 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostPullRequestMergeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPullRequestMergeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostPullRequestReassignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Pr PullRequest `json:"pr"`

		// ReplacedBy user_id нового ревьювера
		ReplacedBy string `json:"replaced_by"`
	}
	JSON404 *ErrorResponse
	JSON409 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostPullRequestReassignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPullRequestReassignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTeamAddResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		Team *Team `json:"team,omitempty"`
	}
	JSON400 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostTeamAddResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTeamAddResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTeamGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Team
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetTeamGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTeamGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersGetReviewResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		PullRequests []PullRequestShort `json:"pull_requests"`
		UserId       string             `json:"user_id"`
	}
}

// Status returns HTTPResponse.Status
func (r GetUsersGetReviewResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersGetReviewResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostUsersSetIsActiveResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		User *User `json:"user,omitempty"`
	}
	JSON404 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostUsersSetIsActiveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostUsersSetIsActiveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostPullRequestCreateWithBodyWithResponse request with arbitrary body returning *PostPullRequestCreateResponse
func (c *ClientWithResponses) PostPullRequestCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestCreateResponse, error) {
	rsp, err := c.PostPullRequestCreateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestCreateResponse(rsp)
}

func (c *ClientWithResponses) PostPullRequestCreateWithResponse(ctx context.Context, body PostPullRequestCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestCreateResponse, error) {
	rsp, err := c.PostPullRequestCreate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestCreateResponse(rsp)
}

// PostPullRequestMergeWithBodyWithResponse request with arbitrary body returning *PostPullRequestMergeResponse
func (c *ClientWithResponses) PostPullRequestMergeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestMergeResponse, error) {
	rsp, err := c.PostPullRequestMergeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestMergeResponse(rsp)
}

func (c *ClientWithResponses) PostPullRequestMergeWithResponse(ctx context.Context, body PostPullRequestMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestMergeResponse, error) {
	rsp, err := c.PostPullRequestMerge(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestMergeResponse(rsp)
}

// PostPullRequestReassignWithBodyWithResponse request with arbitrary body returning *PostPullRequestReassignResponse
func (c *ClientWithResponses) PostPullRequestReassignWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestReassignResponse, error) {
	rsp, err := c.PostPullRequestReassignWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestReassignResponse(rsp)
}

func (c *ClientWithResponses) PostPullRequestReassignWithResponse(ctx context.Context, body PostPullRequestReassignJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestReassignResponse, error) {
	rsp, err := c.PostPullRequestReassign(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestReassignResponse(rsp)
}

// PostTeamAddWithBodyWithResponse request with arbitrary body returning *PostTeamAddResponse
func (c *ClientWithResponses) PostTeamAddWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTeamAddResponse, error) {
	rsp, err := c.PostTeamAddWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTeamAddResponse(rsp)
}

func (c *ClientWithResponses) PostTeamAddWithResponse(ctx context.Context, body PostTeamAddJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTeamAddResponse, error) {
	rsp, err := c.PostTeamAdd(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTeamAddResponse(rsp)
}

// GetTeamGetWithResponse request returning *GetTeamGetResponse
func (c *ClientWithResponses) GetTeamGetWithResponse(ctx context.Context, params *GetTeamGetParams, reqEditors ...RequestEditorFn) (*GetTeamGetResponse, error) {
	rsp, err := c.GetTeamGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTeamGetResponse(rsp)
}

// GetUsersGetReviewWithResponse request returning *GetUsersGetReviewResponse
func (c *ClientWithResponses) GetUsersGetReviewWithResponse(ctx context.Context, params *GetUsersGetReviewParams, reqEditors ...RequestEditorFn) (*GetUsersGetReviewResponse, error) {
	rsp, err := c.GetUsersGetReview(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersGetReviewResponse(rsp)
}

// PostUsersSetIsActiveWithBodyWithResponse request with arbitrary body returning *PostUsersSetIsActiveResponse
func (c *ClientWithResponses) PostUsersSetIsActiveWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUsersSetIsActiveResponse, error) {
	rsp, err := c.PostUsersSetIsActiveWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUsersSetIsActiveResponse(rsp)
}

func (c *ClientWithResponses) PostUsersSetIsActiveWithResponse(ctx context.Context, body PostUsersSetIsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUsersSetIsActiveResponse, error) {
	rsp, err := c.PostUsersSetIsActive(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUsersSetIsActiveResponse(rsp)
}

// ParsePostPullRequestCreateResponse parses an HTTP response from a PostPullRequestCreateWithResponse call
func ParsePostPullRequestCreateResponse(rsp *http.Response) (*PostPullRequestCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPullRequestCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			Pr *PullRequest `json:"pr,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParsePostPullRequestMergeResponse parses an HTTP response from a PostPullRequestMergeWithResponse call
func ParsePostPullRequestMergeResponse(rsp *http.Response) (*PostPullRequestMergeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPullRequestMergeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Pr *PullRequest `json:"pr,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostPullRequestReassignResponse parses an HTTP response from a PostPullRequestReassignWithResponse call
func ParsePostPullRequestReassignResponse(rsp *http.Response) (*PostPullRequestReassignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPullRequestReassignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Pr PullRequest `json:"pr"`

			// ReplacedBy user_id нового ревьювера
			ReplacedBy string `json:"replaced_by"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParsePostTeamAddResponse parses an HTTP response from a PostTeamAddWithResponse call
func ParsePostTeamAddResponse(rsp *http.Response) (*PostTeamAddResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTeamAddResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			Team *Team `json:"team,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetTeamGetResponse parses an HTTP response from a GetTeamGetWithResponse call
func ParseGetTeamGetResponse(rsp *http.Response) (*GetTeamGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTeamGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Team
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetUsersGetReviewResponse parses an HTTP response from a GetUsersGetReviewWithResponse call
func ParseGetUsersGetReviewResponse(rsp *http.Response) (*GetUsersGetReviewResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersGetReviewResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			PullRequests []PullRequestShort `json:"pull_requests"`
			UserId       string             `json:"user_id"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostUsersSetIsActiveResponse parses an HTTP response from a PostUsersSetIsActiveWithResponse call
func ParsePostUsersSetIsActiveResponse(rsp *http.Response) (*PostUsersSetIsActiveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostUsersSetIsActiveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			User *User `json:"user,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(ctx echo.Context) error
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(ctx echo.Context) error
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(ctx echo.Context) error
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(ctx echo.Context) error
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(ctx echo.Context, params GetTeamGetParams) error
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(ctx echo.Context, params GetUsersGetReviewParams) error
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostPullRequestCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestCreate(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestCreate(ctx)
	return err
}

// PostPullRequestMerge converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestMerge(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestMerge(ctx)
	return err
}

// PostPullRequestReassign converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestReassign(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestReassign(ctx)
	return err
}

// PostTeamAdd converts echo context to params.
func (w *ServerInterfaceWrapper) PostTeamAdd(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTeamAdd(ctx)
	return err
}

// GetTeamGet converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeamGet(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams
	// ------------- Required query parameter "team_name" -------------

	err = runtime.BindQueryParameter("form", true, true, "team_name", ctx.QueryParams(), &params.TeamName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter team_name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeamGet(ctx, params)
	return err
}

// GetUsersGetReview converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersGetReview(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams
	// ------------- Required query parameter "user_id" -------------

	err = runtime.BindQueryParameter("form", true, true, "user_id", ctx.QueryParams(), &params.UserId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersGetReview(ctx, params)
	return err
}

// PostUsersSetIsActive converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSetIsActive(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSetIsActive(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	router.POST(baseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	router.POST(baseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)
	router.POST(baseURL+"/team/add", wrapper.PostTeamAdd)
	router.GET(baseURL+"/team/get", wrapper.GetTeamGet)
	router.GET(baseURL+"/users/getReview", wrapper.GetUsersGetReview)
	router.POST(baseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xabW8bxxH+K4ttgTgALVK0XaD8xtiKqg+WWYoGigqCsOKtpEvuzXd7agSDgF7Suq2M",
	"qvlWBEiMwH+ApsWK1gv1F2b/UTG7R94deTxRpiwX+WJTx73d2dlnnnlmli9p07U91+GOCGjlJfWYz2wu",
	"uK/+anBmLzOb/zHk/i4+MHjQ9E1PmK5DKxTewiX04AzacC5fwyX0oUugBxfymMAZ9OEC2nAJJ/KIFqiJ",
	"b7xQExWow2xOK1RwZq+rzwXq8xeh6XODVoQf8gINmtvcZrio2PVwcCB809mirVaBPg+4v2RMsuo/cAJd",
	"uJQH0JPfa/vkAfTlHoEr6CtTT6EPHfW4C+fyeIJ5YcD9ddO4kXGtwZfKgQu+7/p1HniuE3B8wL9jtmfp",
	"j/gdfmi6Bk6x/Kyx/vWz58tPaIHaPAjYFj71eeCGfpMTxxVk0w0dQ3nA812P+8LkQWqq9GM98UvKndCm",
	"lVXaWKg+XV/409JKY4UWaK2e+vx0ob64gGujHdWVlaXF5ejP9cfV5SdLT6qNhehbbeVaYXTzCbuzTi12",
	"4qo2LR4fz+VufMObYmy83uH4sAKthZZV5y9CHohxD7AgMLccbqz7fMfkf4lgncZLdMoELqENp/ivfIX4",
	"gUt5JP9K5B50oSNfy39BB7pyD5FD7pXm5spfImwEt4OM7Q4NZb7PdvFvFoptV8Epa3TT50xwo6r2sOn6",
	"NhO0Qg0m+H1hqvhwQstiGwgdDcEM3/tbs83ghZa17mtfTjI0NUbHScaoQDARBknsPastLNMCjVA2jp2R",
	"8x41JWvhpE+HSxayzvwa3Kxsu34WeHJP7NfgrCy/IOeP+8Lm9kYUPUPI/9bnm7RCf1OMU0gx4r4izvJU",
	"vZMVCzHvX0sUyRQxMGKS2dGCY8abwTprCnMnudyG61qcOfjqgOazzga/m87QOFkM3ykkVs6yGdPYja3N",
	"890n3UvyJPL2hZOZzqarljEF8g2t1Uk9ikZSVfFpc0eQFe7vmE1O7jV4IEiDBd8WyNfMski5VH6E9LrD",
	"/UCz9Pxcaa6Eu3A97jDPpBX6YK409wDBzsS28lzRi2O6qBlVudfVqQGdzJD0lww0yQ1EggMe6+HaDzwQ",
	"X7nGrs6hjuCOep95nmU21QzFbwK0KpXPE3RBw3mawRDU8+/Pl0rzmQFaoVXDIAFnfnObtpIS43Ow0owM",
	"k42KtIpSD7QyUhsrl+Zv5nDPn5TiV2lYRvA+QENu81xistYc3co5KG1eHkkmpUurlemytFSp1Ynchz6c",
	"wgkqazzMh6WHU3gttjHPnrRazVgf/g0dLaWLSX0PbRRPXa2gPkTq+0hb9/ubnemoKE6K1FgU1+rENAiz",
	"fM6MXcK/MwMRjJzFTPtEPx/Cf6FL5L48lP+ArtyXB9CRh9CVB3ql0LYZlh8UfhmciDyQr0mtTqBHoK09",
	"hS5ShcgrnAPO8Kukzuypd+AE+qScLTWhB6cj1dRwdrkHbWRmtqVAn8BTQNfQyhQjKoE4NSE+VaNn4MPJ",
	"YZYXNNfy1zXM9HHMU7ob5oklOsUMd3++dL/8sDFfrjx4WHn0uz/fGjdFwvHu2Qk6iqBUtPTlsWoP9MjA",
	"nDtmK7RnlJZGY/eNiquuCtFB9J5BG84io8k96Kk3L+AK+qpfcCkPVPAeE+jDlYrTtvwb9OTxl9PHos81",
	"eqYOx/rghRki0rVirEaoLOdiLgc/OFee2Jw5kAupJT5/WKPSDB99ckGBe/As1uTG+gYiNHxEby+KRybP",
	"6YT0oQN9eA/98aSkMk7+Ufo0vdLaFOwBb9Ts3bE2TA9DuCOPdPMOIxrt+yxs0oNzTODZXcTXWWxzQwkU",
	"1dqYJZTpMVH9pNeAU+SdC0VDx1o7IC/twzl0ybCFt8OscJKcGg6K5VSTOY4ryICTiOsQbQOp1bUrHPcx",
	"cwzTiCqqtF3yQAkYJH15CFdR30zRKIrDnpZG6Ks800b6jLF1jkt0rUkiSKnSsTmwh5gOwdJ0YKioRvE7",
	"Yuib3EN7J4/gfKwFmKXILvI3keqdJtu4UfVrBqqTOyAZIlwits0g8vTtSVj4CdpyTx7Kv8dBdKKT3bC1",
	"CVcYztBBXJMolWXEnzwez5rjQyMli0L1Es7wa5UnJ5GI8jWBE7QRh6hhWut29efRC4SczIrnX2SGkZ9N",
	"G5zZVcOYJYMO22CrqT6N7qcO06HOCnG7hVYts8lpq5D/Ujn90lfuBm2tpRo+1GO7trqqmRoojWFo3HL1",
	"LaI+4ed2yQZrfsujW5FJaXJg6xSOmiZT/ZgqfZMVObQ15Zdmq3rTFzUxiwz3/Qlr39HdfWwdnIrfQyL3",
	"iTyUr6CtZhhcG15Aj9yLHSh/kAdF6MO7SIGcy2OdXjIzLnThQ1Jy4wmmGGGLK+dH/6UJYZErPljkQnUQ",
	"41vP1Wz/xUOK6VtRxONssvP/JoJuzikj0PkZ3sl/QhfO8MzS/H3nraof8/tTGKnjpeC5wmjvRgCegEB0",
	"eoAQ1I3vPCA+x6GLw5E3xWPyNnx2NCYLFr38J6131kbQOmVvaPqbqLF7voz7qMmF7MSLkbQxUxU4v8AV",
	"9BTZnZFa/Qvd3Zv0i4RrwFmrfyGPCgTeI5pzK5KpBO0AwAqJKQAHXCwF1eF91GR1pV5dSYyeQWYlCG2T",
	"WQGfHiMffdU38aCvu+q65R5EGN0Jjrsgi7KvpfocVw1WygsedUM5nSj6OZG1f9AlBnyYiMy7zwdvpi/a",
	"06H3VhF+O9qcDj/5PZxDG94TaGOygx508Hs1spf3M6OxQGsNn70c/OxIZxFM7NEDPTjxIFUCJZ7/gTNL",
	"bNPWWut/AQAA//80B9xs2CUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
